config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :dashboard, only: [:show]
  root "static_pages#index"
  resources :games do
  	member do
  		post :forfeit_game
  	end
  end

  resources :pieces, only: [:update]
  resources :dashboards, only: :show

end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user_black, class_name: 'User', foreign_key: 'user_id_black', optional: true
  belongs_to :user_white, class_name: 'User', foreign_key: 'user_id_white', optional: true
  has_many :pieces
  has_many :moves

  scope :available, (-> { where(status: 'available') })

  def missing_player_color
    if user_id_black.nil?
      'Black'
    else
      'White'
    end
  end

  def host_player
    user_black || user_white
  end

  def reset_piece_players
    pieces.where(is_black: true).update_all(user_id: user_id_black)
    pieces.where(is_black: false).update_all(user_id: user_id_white)
  end
  # rubocop:disable MethodLength
  # rubocop:disable Metrics/AbcSize

  def initialize_board
    # Building out white pieces
    (0..7).each do |x|
      Pawn.create(is_black: false, x_position: x, y_position: 1, game_id: id, user_id: user_id_white, status: 'active')
    end

    Rook.create(is_black: false, x_position: 0, y_position: 0, game_id: id, user_id: user_id_white, status: 'active')
    Rook.create(is_black: false, x_position: 7, y_position: 0, game_id: id, user_id: user_id_white, status: 'active')

    Knight.create(is_black: false, x_position: 1, y_position: 0, game_id: id, user_id: user_id_white, status: 'active')
    Knight.create(is_black: false, x_position: 6, y_position: 0, game_id: id, user_id: user_id_white, status: 'active')

    Bishop.create(is_black: false, x_position: 2, y_position: 0, game_id: id, user_id: user_id_white, status: 'active')
    Bishop.create(is_black: false, x_position: 5, y_position: 0, game_id: id, user_id: user_id_white, status: 'active')

    King.create(is_black: false, x_position: 4, y_position: 0, game_id: id, user_id: user_id_white, status: 'active')
    Queen.create(is_black: false, x_position: 3, y_position: 0, game_id: id, user_id: user_id_white, status: 'active')

    # Building out the black pieces
    (0..7).each do |x|
      Pawn.create(is_black: true, x_position: x, y_position: 6, game_id: id, user_id: user_id_black, status: 'active')
    end

    Rook.create(is_black: true, x_position: 0, y_position: 7, game_id: id, user_id: user_id_black, status: 'active')
    Rook.create(is_black: true, x_position: 7, y_position: 7, game_id: id, user_id: user_id_black, status: 'active')

    Knight.create(is_black: true, x_position: 1, y_position: 7, game_id: id, user_id: user_id_black, status: 'active')
    Knight.create(is_black: true, x_position: 6, y_position: 7, game_id: id, user_id: user_id_black, status: 'active')

    Bishop.create(is_black: true, x_position: 2, y_position: 7, game_id: id, user_id: user_id_black, status: 'active')
    Bishop.create(is_black: true, x_position: 5, y_position: 7, game_id: id, user_id: user_id_black, status: 'active')

    King.create(is_black: true, x_position: 4, y_position: 7, game_id: id, user_id: user_id_black, status: 'active')
    Queen.create(is_black: true, x_position: 3, y_position: 7, game_id: id, user_id: user_id_black, status: 'active')
  end

  def checkmate?(is_black)
    king = pieces.find_by(type: 'King', is_black: is_black)

    return false unless king.in_check?

    return false unless stalemate(is_black)

    true
  end

  # detects stalemate for color of current piece within game.
  # Runs through an array of certain color's active pieces and checks to see if there ar any valid moves available
  def stalemate(is_black)
    active_pieces = pieces_active(is_black)

    active_pieces.each do |piece|
      (0..7).each do |x|
        (0..7).each do |y|
          return false if piece.move_valid?(x, y) && piece.move_causes_check?(x, y) == false
          true
        end
      end
    end
    true
  end # returns an array of a color's active pieces

  def pieces_active(is_black)
    pieces.where('is_black = ? AND status = ?', is_black, 'active')
  end

  def game_in_check?
    white_king = pieces.where('is_black = ? AND type = ?', false, 'King').first
    black_king = pieces.where('is_black = ? AND type = ?', true, 'King').first

    return true if white_king.in_check? || black_king.in_check?
    # return true if king.in_check?
    false
  end

  def turn
    return user_id_white if moves.count.even?
    user_id_black
  end

  # rubocop:enable Metrics/AbcSize
  # rubocop:enable MethodLength
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @available_games = Game.available
    @game = Game.new
  end

  def create
    @game = Game.create(game_params.merge(status: 'available'))
    @game.initialize_board
    redirect_to game_path(@game)
  end

  def update
    @game = Game.find(params[:id])
    @game.update_attributes(game_params.merge(status: 'active'))
    @game.reset_piece_players
    redirect_to game_path(@game)
  end

  def show
    @game = Game.find(params[:id])

    @moves = @game.moves
  end

  def forfeit_game
    @game = Game.find(params[:id])

    if @game.user_id_black == current_user.id
      @game.update_attributes(status: 'Forfeit', winner: @game.user_id_white)
    else
      @game.update_attributes(status: 'Forfeit', winner: @game.user_id_black)
    end

    redirect_to game_path(@game.id)
  end

  private

  def game_params
    params.require(:game).permit(:user_id_black, :user_id_white)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<br />
<div class="booyah-box col-10 offset-1">
  <h1>Games</h1>
  <div class="container">
    <div class="panel panel-default">
      <div class="panel-heading"><b>Available Games</b></div>
      <table class="table">
        <tr>
          <th>Game ID</th>
          <th>Player</th>
          <th>You would be...</th>
        </tr>
        <% @available_games.each do |available_game| %>
          <tr>
            <td><%= available_game.id %></td>
            <td><%= available_game.host_player.email %></td>
            <td><%= available_game.missing_player_color %></td>

            <td>      <%= simple_form_for available_game do |f| %>

            <%= f.hidden_field available_game.missing_player_color == 'White' ?
              :user_id_white : :user_id_black, value: current_user.id %>

            <%= f.submit available_game.missing_player_color == 'White' ? "Join as White" : "Join as Black", class: 'btn btn-primary button-small' %>
            <br />
            <% end %>
           </td>
          </tr>
        <% end %>
      </table>
    </div>
    <div class="panel-heading"><b>Completed Games</b></div>
      <table class="table">
        <tr>
          <th>Game ID</th>
          <th>White Player</th>
          <th>Black Player</th>
          <th>Outcome</th>
        </tr>
      </table>
    </div>
  </div>
</div>

app/views/games/show.html.erb
</br>
</br>

<h1>Chessboard</h1>

<table id='chessboard'>
  <% ((7).downto(0)).each do |y| %>
    <tr>
    <% (0..7).each do |x| %>
      <td class="droppable" data-x="<%= x %>" data-y="<%= y %>">
      <% piece = Piece.find_by(x_position: x, y_position: y, game_id: @game.id) %>
      	<% if piece.present? %>
      		<div class="piece draggable" data-black="<%= piece.is_black %>" data-id="<%= piece.id %>" data-status="<%= piece.game.status %>"><%= piece.unicode.html_safe %></div>
        <% end %>
      </td>
    <% end %>
  <% end %>
</table>
<br />

<%= link_to 'Forefeit Game', forfeit_game_game_path, method: :post, data: {confirm: 'Are you sure you want to forfeit?'},class: 'btn btn-secondary' %>

    <table class="table text-center">
      <h2 class= 'text-center'>&nbsp;&nbsp; Moves</h3>
        <tr>
          <th>Move Number</th>
          <th>White's Move</th>
          <th>Black's Move</th>
        </tr>
        <% if @moves %>
          <% @moves.each_slice(2).each_with_index do |pair, index| %>
              <tr>
                  <td><%= index + 1 %></td>
                  <% if pair[0] %>
                    <td><%= pair[0].to_algebra.html_safe %></td>
                  <% end %>
                  <% if pair[1] %>
                    <td><%= pair[1].to_algebra.html_safe %> </td>
                  <% end %>
              </tr>
          <% end %>
        <% end %>
    </table>


<script>
  $(document).ready(function () {
    $(".draggable").draggable({
      helper: "clone",
    });
    $(".droppable").droppable({

      drop: function( event, ui) {

        var id = ui.draggable.data('id')
        var x = $(this).data('x')
        var y = $(this).data('y')


        $.ajax({
          type: 'PUT',
           url: '/pieces/' + id,
           dataType: 'json',
           data: { id: id, x_position: x, y_position: y },
           success: function(data){
             location.reload();
          }
        });
      }
    });
  });
</script>

<script>
$(document).ready(function () {
<% if @game.status != "available" && @game.status != "active" %>
    $('#myModal').modal('show');
<% end %>
});
</script>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Game Over!</h4>
      </div>
      <div class="modal-body">
        Game Status: <%= @game.status %>
        </br>
        Winner: <strong><%= @game.winner %></strong>
      </div>
      <div class="modal-footer">
        <%= link_to 'Start a new game!', root_path, class: "btn btn-secondary" %>
      </div>
    </div>
  </div>
</div>