config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :dashboard, only: [:show]
  root "static_pages#index"
  resources :games do
  	member do
  		post :forfeit_game
  	end
  end

  resources :pieces, only: [:update]
  resources :dashboards, only: :show

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @active_games = current_user.games.where(status: 'active')
    @completed_games = current_user.games.where(status: 'completed')
  end
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/views/dashboards/show.html.erb
<br />

<div class="booyah-box col-10 offset-1">
    <div class="row">
        <div class="col-4">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <%= image_tag '1487990647_Supersushi.png' %>
        </div>
        <div class="col-6"
            <br />
            <br />
            <h1 class='text-center'>My Dashboard</h1>

            <h2 class='text-center'>Username: <%= current_user.name %></h2>
            <h4 class='text-center'>Member Since: <%= current_user.created_at.strftime("%B %d, %Y") %> </h4>
        </div>
    </div>
    <hr />
    <div class="col-8 offset-2">
        <br />
        <h3 class='text-center'>Games I'm Currently Playing</h3>
        <br />
          <div class="container">
            <div class="panel panel-default">
              <div class="panel-heading"></div>
                  <table class="table">
                    <tr class="heading">
                      <th>#</th>
                      <th>Playing White</th>
                      <th>Playing Black</th>
                    </tr>
                    <% if @active_games %>
                        <% @active_games.each do |game| %>
                          <tr>
                            <td><%= game.id %></td>
                            <td><%= game.user_white.name %></td>
                            <td><%= game.user_black.name %></td>
                            <td><%= link_to 'View Game', game_path(game.id), class: 'button' %></td>
                          </tr>
                        <% end %>
                    <% end %>
                  </table>
              </div>
            </div>
        <br />
        <br />
          <h3 class='text-center'>Games I've Completed</h3>
          <br />
           <div class="container">
            <div class="panel panel-default">
              <div class="panel-heading"></div>
                  <table class="table">
                    <tr class="heading">
                      <th>#</th>
                      <th>Playing White</th>
                      <th>Playing Black</th>
                      <th>Outcome</th>
                    </tr>
                    <% if @completed_games %>
                        <% @completed_games.each do |game| %>
                          <tr>
                            <td><%= game.id %></td>
                            <td><%= game.user_white.name %></td>
                            <td><%= game.user_black.name %></td>
                            <td><%= game.winner %></td>
                          </tr>
                        <% end %>
                    <% end %>
                  </table>
              </div>
            </div>
    </div>
</div>