config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :dashboard, only: [:show]
  root "static_pages#index"
  resources :games do
  	member do
  		post :forfeit_game
  	end
  end

  resources :pieces, only: [:update]
  resources :dashboards, only: :show

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chessapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="flex-content-container">
        <nav class="navbar navbar-fixed-top navbar-toggleable-md navbar-inverse bg-inverse">
          <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <%= link_to 'Wookie Chess!', root_path, class: 'navbar-brand' %>
          <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto mt-2 mt-md-0">
              <li>
                <%= link_to 'Home', root_path, class:'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to 'Games Page', games_path, class:'nav-link' %>
              </li>
            </ul>
            <ul class="navbar-nav">
              <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'My Dashboard', dashboard_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class:'nav-link' %>
                </li>
              <% else %>
                <li class="nav-item">
                    <%= link_to 'Log in',new_user_session_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to 'Sign up', new_user_registration_path, class:'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, class:'nav-link' %>
                </li>
              <% end %>
            </ul>
          </div>
        </nav>
        <% if notice.present? %>
          <p class="alert alert-info"><%= notice %></p>
        <% end %>

        <% if alert.present? %>
        <p class="alert alert-danger"><%= alert %></p>
        <% end %>


          <% if flash[:error].present? %>
            <div class="col-10 offset-1 alert alert-danger">
              <%= flash[:error].html_safe %>
            </div>
          <% end %>




        <%= yield %>

    </div>